### ISSUE TITLE
sdpb --help: Print current SDPB version

### ISSUE THREAD

**Issue by vasdommes** [davidsd/sdpb#140]

**Comment by bharathr98** [comment]
I believe this is a simple enough fix. Since SDPB_VERSION_STRING is already defined (see line 96 in SDPB_Parameters.cxx for example), it just involves adding an extra cout line in this block ⬇️
https://github.com/davidsd/sdpb/blob/7a12e6169f017036b853a82bf78021c6099a7794/src/sdpb/SDPB_Parameters/SDPB_Parameters.cxx#L85-L91

I can go ahead and do that and submit a pull request if that sounds good...

**Comment by vasdommes** [comment]
@bharathr98 sounds good, you're welcome to submit a PR!
