### ISSUE TITLE
sdpb produces too many output files

### ISSUE THREAD

**Issue by eschnett** [davidsd/sdpb#39]
We have a user on our local HPC system running sdpb, and recently discovered that he had produced 100M (100 million) output files. This is causing problems for us because there is a limit on the number of inodes (files) that our file system can support. In addition, writing many small files is much less efficient than writing fewer larger files.

Do you have any plans for creating fewer, larger files? Depending on the output format, either HDF5, JSON, YAML etc. might be good candidates for this, which have widely used, mature libraries.

I would be happy to assist with implementing this (if this makes sense).

**Comment by wlandry** [comment]
This is a problem that a few other people are running into.  SDPB writes two kinds of files: checkpoints and final output.  Which files are causing the problems?  If it is the final output, you can work around it by tar'ing or zip'ing the output directory as a post processing step.

We could automate this by having SDPB create the zip archive.  As I understand it, people modify these  output files and use that as a checkpoint.  So I am wary of making the output format any more complicated than it is.

To be clear, the proper way to do this would be to write a single HDF5 file. It would have the added benefit of allowing us to include metadata.  However, this would definitely make the output harder to work with.  It would also make it more difficult to build SDPB, and open up new failure modes.  We have been seeing lots of problems with filesystems, so I am reluctant to add this kind of complexity.

**Comment by eschnett** [comment]
@wlandry I don't know which files are causing the problem, and I don't think that the respective user does, either. Although I explicitly stated (twice) that the number, not the size of the files was the problem, he proceeded to delete output files instead of zipping them.

Since I am not familiar with the workflow used for sdpb, I can't give good advice. It would be very helpful if there was documentation for this problem and suggested example solutions. Can you point me to a respective example, e.g. a Slurm batch script?

Is there a reason why checkpointing files cannot be zipped? Are they already zipped? Presumably they could easily be unzipped before the next run starts, and these unzipped files then be deleted after the run finishes.

HDF5 is a binary format, which is difficult to modify. JSON would still be human readable, can easily be read and written without external dependencies, and would support metadata. YAML is another format that is easily be written (but is more difficult to read).

**Comment by wlandry** [comment]
There might also be a problem with input files.  The output of `pvm2sdp` creates a lot of files.  If you want to get rid of all of the input files but keep the checkpoints and output, you can use something like this in your SLURM batch script.

```
srun -n $SLURM_NTASKS pvm2sdp 1024 myrun.xml myrun
srun -n $SLURM_NTASKS sdpb --precision=1024 --procsPerNode=$SLURM_JOB_CPUS_PER_NODE -s myrun`
rm -rf myrun
zip -rm myrun.ck.zip myrun.ck
zip -rm myrun_out.zip myrun_out
```

The details will vary depending on your installation.  You could also delete everything.  It depends on what you want to keep.  Everyone wants to keep different things.

JSON only helps with metadata.  It still would not allow us to write to a single file from all of the cores without very expensive and error prone file locking. HDF5 is really the proper way to do parallel IO to a single file.

I am curious: how many jobs did the user run in order to generate 100 million files?  I would expect, at most, a few thousand files per run, which means they ran something like 50,000 jobs?  Are they generating a large number of XML files before running `pvm2sdp` and `sdpb`?

**Comment by wlandry** [comment]
I managed to talk to the user who generated all of these files.  it turns out that they have about 20,000 blocks, many of which are tiny (1x1).  This is different from what I am familiar with.  In any event, they only use `out.txt`.  They do not use the vector outputs (`y.txt` and `x_*.txt`), and there are 20,000 of these.  So I think it might be best to add an option `--writeVectors` which defaults to true.  Then they could set it to false and only get the `out.txt` file.

In the meantime, the user now knows that they have to delete these files after every run.

**Comment by eschnett** [comment]
Thanks!

**Comment by davidsd** [comment]
Hi Walter, I think this is a case where we might need more fine-grained control of which vectors are printed. Specifically, I can easily imagine a use-case where we need to read out the dual functional (y.txt), but we do not need the primal vector x. Since the primal vector is the one causing the difficulty in this case, we might need to add two options --writeVectorx and --writeVectory, both defaulting to true.

**Comment by davidsd** [comment]
The user can now control what parts of the solution are written to disk with the --writeSolution option.
